export const TOUR_IDS = ["home", "workspace", "settings", "ai", "diagram"] as const;

export type TourId = (typeof TOUR_IDS)[number];
export type TourStatus = "pending" | "completed" | "dismissed";
export type TourContext = "home" | "project" | "settings" | "ai" | "diagram";
export type TourStepKind = "informational" | "required-click" | "required-input" | "transition";

export interface TourStepDefinition {
  id: string;
  target: `[data-tour="${string}"]`;
  interactionTarget?: `[data-tour="${string}"]`;
  interactionArea?: `[data-tour="${string}"]`;
  spotlightTarget?: `[data-tour="${string}"]`;
  kind: TourStepKind;
  title: string;
  content: string;
  waitForTarget?: boolean;
  placement?: "center" | "top" | "bottom" | "left" | "right" | "bottom-end";
}

export interface TourDefinition {
  id: TourId;
  version: number;
  contexts: readonly TourContext[];
  priority: number;
  steps: readonly TourStepDefinition[];
}

export const tourRegistry = {
  home: {
    id: "home",
    version: 4,
    contexts: ["home"],
    priority: 10,
    steps: [
      {
        id: "home-overview",
        target: '[data-tour="home"]',
        kind: "informational",
        title: "Home",
        content: "Your projects and project creation begin here.",
        waitForTarget: true,
        placement: "center",
      },
      {
        id: "home-create",
        target: '[data-tour="new-project"]',
        kind: "required-click",
        title: "Create a real project",
        content: "Choose New project to open the template gallery.",
        waitForTarget: true,
        placement: "bottom-end",
      },
      {
        id: "home-gallery",
        target: '[data-tour="project-template-gallery"]',
        kind: "informational",
        title: "Find your starting point",
        content: "Browse categories, search by name, and narrow templates by compiler or offline availability.",
        waitForTarget: true,
        placement: "center",
      },
      {
        id: "home-template",
        target: '[data-tour="project-template-gallery"]',
        interactionTarget: '[data-tour="project-template-card"]',
        interactionArea: '[data-tour="project-template-gallery"]',
        kind: "required-click",
        title: "Choose a template",
        content: "Select any real template to continue. Its files will become your new project.",
        waitForTarget: true,
        placement: "left",
      },
      {
        id: "home-name",
        target: '[data-tour="project-name"]',
        kind: "required-input",
        title: "Name your project",
        content: "Enter a project name. Next becomes available when the name is not empty.",
        waitForTarget: true,
        placement: "bottom",
      },
      {
        id: "home-color",
        target: '[data-tour="project-cover-color"]',
        interactionArea: '[data-tour="project-cover-color"]',
        kind: "informational",
        title: "Choose a cover color",
        content: "This color makes the project easy to spot on Home. You can keep the template default.",
        waitForTarget: true,
        placement: "top",
      },
      {
        id: "home-create-project",
        target: '[data-tour="create-project"]',
        kind: "required-click",
        title: "Open your workspace",
        content: "Create the project with the selected template, name, and cover color.",
        waitForTarget: true,
        placement: "top",
      },
    ],
  },
  workspace: {
    id: "workspace",
    version: 3,
    contexts: ["project"],
    priority: 20,
    steps: [
      {
        id: "workspace-toolbar",
        target: '[data-tour="project-toolbar"]',
        kind: "informational",
        title: "Project toolbar",
        content: "Project actions and compilation controls live here.",
        waitForTarget: true,
        placement: "bottom",
      },
      {
        id: "workspace-sidebar",
        target: '[data-tour="project-sidebar"]',
        kind: "informational",
        title: "Workspace navigation",
        content: "Move between files, search, source control, preflight, AI, integrations, and project tools.",
        waitForTarget: true,
        placement: "right",
      },
      {
        id: "workspace-editor",
        target: '[data-tour="project-editor"]',
        kind: "informational",
        title: "Editor",
        content: "Write and navigate source with completion, diagnostics, formatting, and code intelligence.",
        waitForTarget: true,
        placement: "right",
      },
      {
        id: "workspace-compile",
        target: '[data-tour="project-compile"]',
        kind: "informational",
        title: "Compile and recompile",
        content: "Build the current project here. The tour never compiles or changes your source.",
        waitForTarget: true,
        placement: "bottom-end",
      },
      {
        id: "workspace-logs",
        target: '[data-tour="project-compile-logs"]',
        kind: "informational",
        title: "Build logs",
        content: "Open build logs to inspect errors without changing project content. The adjacent status shows the latest compile time.",
        waitForTarget: true,
        placement: "bottom",
      },
      {
        id: "workspace-preview",
        target: '[data-tour="project-preview"]',
        kind: "informational",
        title: "PDF preview",
        content: "The compiled document stays beside your source in split view.",
        waitForTarget: true,
        placement: "left",
      },
      {
        id: "workspace-zoom",
        target: '[data-tour="project-preview-zoom"]',
        kind: "informational",
        title: "Preview controls",
        content: "Adjust zoom, search the document, and export the PDF from the preview toolbar.",
        waitForTarget: true,
        placement: "bottom",
      },
      {
        id: "workspace-source-navigation",
        target: '[data-tour="project-preview-content"]',
        kind: "informational",
        title: "PDF to source",
        content: "Click compiled PDF content to jump directly to the corresponding source.",
        waitForTarget: true,
        placement: "left",
      },
    ],
  },
  settings: {
    id: "settings",
    version: 2,
    contexts: ["settings"],
    priority: 30,
    steps: [
      {
        id: "settings-navigation",
        target: '[data-tour="settings-navigation"]',
        spotlightTarget: '[data-tour="settings-navigation-panel"]',
        kind: "informational",
        title: "Settings",
        content: "Move between preferences and integrations here.",
        waitForTarget: true,
        placement: "right",
      },
      {
        id: "settings-general",
        target: '[data-tour="settings-general"]',
        spotlightTarget: '[data-tour="settings-general-panel"]',
        kind: "transition",
        title: "General preferences",
        content: "Control editing behavior, offline mode, shortcuts, and tour guides.",
        waitForTarget: true,
        placement: "left",
      },
      {
        id: "settings-appearance",
        target: '[data-tour="settings-appearance"]',
        spotlightTarget: '[data-tour="settings-appearance-panel"]',
        kind: "transition",
        title: "Appearance",
        content: "Choose the theme, typography, default workspace layout, and accent color.",
        waitForTarget: true,
        placement: "left",
      },
      {
        id: "settings-dictionary",
        target: '[data-tour="settings-dictionary"]',
        spotlightTarget: '[data-tour="settings-dictionary-panel"]',
        kind: "transition",
        title: "Dictionary",
        content: "Review project-specific and global words ignored by spelling and grammar checks.",
        waitForTarget: true,
        placement: "left",
      },
      {
        id: "settings-data",
        target: '[data-tour="settings-data"]',
        spotlightTarget: '[data-tour="settings-data-panel"]',
        kind: "transition",
        title: "Data Storage",
        content: "Inspect local project storage and manage application data.",
        waitForTarget: true,
        placement: "left",
      },
      {
        id: "settings-ai",
        target: '[data-tour="settings-ai"]',
        spotlightTarget: '[data-tour="settings-ai-panel"]',
        kind: "transition",
        title: "AI Assistant",
        content: "Configure providers, models, and credentials for the project assistant.",
        waitForTarget: true,
        placement: "left",
      },
      {
        id: "settings-compiler",
        target: '[data-tour="settings-compiler"]',
        spotlightTarget: '[data-tour="settings-compiler-panel"]',
        kind: "transition",
        title: "Compiler",
        content: "Choose and configure the LaTeX engine used to build projects.",
        waitForTarget: true,
        placement: "left",
      },
      {
        id: "settings-downloads",
        target: '[data-tour="settings-downloads"]',
        spotlightTarget: '[data-tour="settings-downloads-panel"]',
        kind: "transition",
        title: "Offline and downloads",
        content: "Manage packages and resources available for offline work.",
        waitForTarget: true,
        placement: "left",
      },
      {
        id: "settings-github",
        target: '[data-tour="settings-github"]',
        spotlightTarget: '[data-tour="settings-github-panel"]',
        kind: "transition",
        title: "GitHub",
        content: "Connect GitHub for remote project backup, synchronization, and source control.",
        waitForTarget: true,
        placement: "left",
      },
      {
        id: "settings-shortcuts",
        target: '[data-tour="settings-shortcuts"]',
        spotlightTarget: '[data-tour="settings-shortcuts-panel"]',
        kind: "transition",
        title: "Keyboard Shortcuts",
        content: "Review, edit, set, and reset application keyboard shortcuts.",
        waitForTarget: true,
        placement: "left",
      },
      {
        id: "settings-mcp",
        target: '[data-tour="settings-mcp"]',
        spotlightTarget: '[data-tour="settings-mcp-panel"]',
        kind: "transition",
        title: "MCP",
        content: "Manage Model Context Protocol connections and available integrations.",
        waitForTarget: true,
        placement: "left",
      },
      {
        id: "settings-help",
        target: '[data-tour="settings-help"]',
        spotlightTarget: '[data-tour="settings-help-panel"]',
        kind: "transition",
        title: "Help and About",
        content: "Restart the contextual tour, open documentation, view shortcuts, or report a problem.",
        waitForTarget: true,
        placement: "left",
      },
    ],
  },
  ai: {
    id: "ai",
    version: 2,
    contexts: ["ai"],
    priority: 40,
    steps: [
      {
        id: "ai-assistant",
        target: '[data-tour="ai-assistant"]',
        kind: "informational",
        title: "AI Assistant",
        content: "Work with a project-aware assistant without sending anything during this tour.",
        waitForTarget: true,
        placement: "right",
      },
      {
        id: "ai-connect-provider",
        target: '[data-tour="ai-connect-provider"]',
        kind: "informational",
        title: "Connect a provider",
        content: "If no provider is configured, start here. The tour never asks for or changes credentials.",
        waitForTarget: true,
      },
      {
        id: "ai-provider-model",
        target: '[data-tour="ai-provider-model"]',
        kind: "informational",
        title: "Provider and model",
        content: "Switch between configured providers and models for this conversation.",
        waitForTarget: true,
      },
      {
        id: "ai-input",
        target: '[data-tour="ai-input"]',
        kind: "informational",
        title: "Chat input",
        content: "Describe what you need. The assistant can use project context, but this tour never sends a request.",
        waitForTarget: true,
      },
      {
        id: "ai-attachments",
        target: '[data-tour="ai-attachments"]',
        kind: "informational",
        title: "Attachments",
        content: "Attach images, PDFs, and source files when a conversation needs extra context.",
        waitForTarget: true,
      },
      {
        id: "ai-history",
        target: '[data-tour="ai-history"]',
        kind: "informational",
        title: "Conversation history",
        content: "Reopen recent and full chat history while keeping each conversation tied to its project state.",
        waitForTarget: true,
      },
      {
        id: "ai-usage",
        target: '[data-tour="ai-usage"]',
        kind: "informational",
        title: "Usage",
        content: "Configured conversations show run, token, and estimated-cost usage here when available.",
        waitForTarget: true,
      },
      {
        id: "ai-restore",
        target: '[data-tour="ai-restore"]',
        kind: "informational",
        title: "Restore project state",
        content: "After an AI edit, a checkpoint can restore project files without removing the conversation.",
        waitForTarget: true,
      },
    ],
  },
  diagram: {
    id: "diagram",
    version: 2,
    contexts: ["diagram"],
    priority: 50,
    steps: [
      {
        id: "diagram-composer",
        target: '[data-tour="diagram-composer"]',
        kind: "informational",
        title: "Diagram Composer",
        content: "Build diagrams visually or from TikZ code. The tour does not modify, compile, or save your work.",
        waitForTarget: true,
        placement: "center",
      },
      {
        id: "diagram-modes",
        target: '[data-tour="diagram-modes"]',
        kind: "informational",
        title: "Draw and Code",
        content: "Draw mode offers direct manipulation; Code mode exposes the generated TikZ and reusable snippets.",
        waitForTarget: true,
      },
      {
        id: "diagram-palette",
        target: '[data-tour="diagram-palette"]',
        kind: "informational",
        title: "Shape palette",
        content: "Choose a shape, then click and drag on the canvas to place and size it.",
        waitForTarget: true,
      },
      {
        id: "diagram-canvas",
        target: '[data-tour="diagram-canvas"]',
        kind: "informational",
        title: "Canvas interactions",
        content: "Move shapes, edit labels, pan with Space and drag, and use the canvas controls to navigate.",
        waitForTarget: true,
        placement: "center",
      },
      {
        id: "diagram-handles",
        target: '[data-tour="diagram-handles"]',
        kind: "informational",
        title: "Connect and resize",
        content: "A selected shape exposes connection and resize handles for precise structure and sizing.",
        waitForTarget: true,
      },
      {
        id: "diagram-inspector",
        target: '[data-tour="diagram-inspector"]',
        kind: "informational",
        title: "Inspector",
        content: "Select a shape or connection to adjust its style, text, routing, and stacking order.",
        waitForTarget: true,
      },
      {
        id: "diagram-preview",
        target: '[data-tour="diagram-preview-affordance"]',
        kind: "informational",
        title: "Compiled preview",
        content: "Compile opens a preview beside the editor with scale and background controls.",
        waitForTarget: true,
        placement: "center",
      },
      {
        id: "diagram-compile",
        target: '[data-tour="diagram-compile"]',
        kind: "informational",
        title: "Compile",
        content: "Compile renders an isolated preview without inserting the diagram into your document.",
        waitForTarget: true,
      },
      {
        id: "diagram-save-project",
        target: '[data-tour="diagram-save-project"]',
        kind: "informational",
        title: "Save as project",
        content: "Save a finished diagram as a reusable image project that appears on Home.",
        waitForTarget: true,
      },
    ],
  },
} as const satisfies Record<TourId, TourDefinition>;

export const TOUR_SCHEMA_VERSION = 1;

export function toursForContext(context: TourContext): TourDefinition[] {
  return Object.values(tourRegistry)
    .filter((tour) => (tour.contexts as readonly TourContext[]).includes(context))
    .sort((a, b) => a.priority - b.priority);
}
